version: "3"
services:
  web:
    build: ./app
    ports:
      - "8080:5000"
    environment:
      - REDIS_NAME=redis
    depends_on:
      - redis
      - rest
  redis:
    image: redis

  rest:
    build: ./rest
    ports:
      - "8081:8081"
