version: "3"
services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - web
      - rest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  web:
    build: ./app
    ports:
      - "8080:5000"
    environment:
      - REDIS_NAME=redis
      - API_HOST=rest
    depends_on:
      - redis
      - rest

  redis:
    image: redis

  rest:
    build: ./rest
    ports:
      - "8081:8081"
