version: "3"
services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - web
      - file-store
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  web:
    build: ./app
    # ports: # Exposed by Nginx
    # - "8080:5000"
    environment:
      - REDIS_NAME=redis
      - FILE_STORE_HOST=file-store
    depends_on:
      - redis
      - file-store

  redis:
    image: redis

  file-store:
    build: ./file-store
    ports:
      - "8081:8081"
